version: '3'

services:
  mssqlserver:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Password123
    image: mcr.microsoft.com/mssql/server
    container_name: 'waiting_list_sql'
    hostname: 'waiting_list_sql'
    restart: always
    ports:
      - "1533:1433"
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-U sa -P Password123 -Q 'SELECT * FROM INFORMATION_SCHEMA.TABLES'" ]
      interval: 10s
      retries: 10
      timeout: 3s
  prospects_test_db:
    container_name: prospects_test_db
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - ./WaitingListTestDb:/project/WaitingListTestDb
    working_dir: /
    environment:
      ProspectsDbConnectionString: "Server=tcp:waiting_list_sql,1433;Database=ProspectsDb;Persist Security Info=False;User ID=sa;Password=Password123;MultipleActiveResultSets=False;Connection Timeout=5;TrustServerCertificate=true;"
    command: "dotnet run --project ./project/WaitingListTestDb/WaitingListTestDb.csproj"
    depends_on:
       mssqlserver:
          condition: service_healthy    